# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np

2. Create a null vector of size 10 

In [2]:
X = np.zeros(10)
print(X)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3. Create a vector with values ranging from 10 to 49

In [3]:
Y = np.arange(10,49)
print(Y)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


4. Find the shape of previous array in question 3

In [4]:
Y.shape

(39,)

5. Print the type of the previous array in question 3

In [5]:
Y.dtype

dtype('int32')

6. Print the numpy version and the configuration


In [6]:
print(np.__version__)
print(np.show_config())

1.18.5
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Kazmis/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/Kazmis/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Kazmis/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\m

7. Print the dimension of the array in question 3


In [7]:
Y.ndim

1

8. Create a boolean array with all the True values

In [12]:
bool_arr = np.ones(5, dtype=bool)
bool_arr

array([ True,  True,  True,  True,  True])

9. Create a two dimensional array




In [13]:
arr2d = np.array([[1,2,3], [4,5,6]])

10. Create a three dimensional array



In [14]:
arr3d = np.array([[[1,2,3], [4,5,6], [7,8,9]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [15]:
new_array = np.arange(1,10)
reverse_array = new_array[::-1]

12. Create a null vector of size 10 but the fifth value which is 1 

In [16]:
arr = np.zeros(10)
arr[5] = 1
arr

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [17]:
matrix = np.arange(9).reshape(3,3)
matrix

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [22]:
arr = np.array([1, 2, 3, 4, 5], dtype='float32')
#arr.astype('float')

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [24]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[0, 4, 1], [7,2,12]])
mul = arr1*arr2

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

17. Extract all odd numbers from arr with values(0-9)

In [25]:
array = np.array([0,1,2,3,4,5,6,7,8,9])
array[array%2!=0]

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [26]:
array[array%2!=0] = -1
array

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [27]:
arr = np.arange(10)
arr[5:9] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [28]:
arr2d = np.ones((5,5))
arr2d[1:4,1:4] = 0
arr2d

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [33]:
arr2d = np.array([[1, 2, 3],[4, 5, 6], [7, 8, 9]])
arr2d[1,1] = 12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [59]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[0:1,0:1] = 64
arr3d

array([[[64, 64, 64],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [70]:
arr2d = np.arange(0,9).reshape(3,3)
arr2d[0:2,::]

array([[0, 1, 2],
       [3, 4, 5]])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [74]:
arr2d = np.arange(0,9).reshape(3,3)
arr2d[1:2,1:2]

array([[4]])

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [78]:
arr2d = np.arange(0,9).reshape(3,3)
arr2d[0:2,2:3]

array([[2],
       [5]])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [85]:
random = np.random.rand(10,10)
random.min(),random.max()

(0.016023688610396936, 0.9795686418428955)

27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [94]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
common_items = np.intersect1d(a,b)
common_items

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [99]:
position = np.where(a==b)
position

(array([1, 3, 5, 7], dtype=int64),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [110]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
data[names!= 'will']

array([[ 0.73096395, -0.27201746, -0.38212683, -0.67314764],
       [ 0.8449741 , -0.1575426 ,  0.26319063,  0.26531402],
       [-1.01867329,  1.2009289 ,  1.12244996,  0.218865  ],
       [-0.7427894 ,  1.00104536,  1.94458039,  0.17659482],
       [ 0.51678425, -0.03834318,  0.06759166, -0.38523971],
       [ 1.36118926, -0.31354154, -1.5036061 ,  0.54669484],
       [ 1.31340809,  0.4782047 ,  0.91483046,  1.78705151]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [111]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
data[names!= 'Joe']

array([[ 0.28022725,  0.05888183,  0.69266531,  0.8783116 ],
       [ 2.37079485,  0.80284105,  1.37936652, -0.83737743],
       [ 1.45537254,  0.0793433 ,  1.05508102,  1.29002606],
       [-0.62735592, -0.79016134, -0.3065051 ,  0.60385966]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [125]:
arr2d = np.random.uniform(1,15, size=(5,3))
arr2d

array([[ 6.60462702,  1.77732176,  6.84090986],
       [ 4.81325521, 13.35933005,  2.49145735],
       [ 2.50619701,  9.36888162,  1.64027933],
       [11.35354913, 14.63502773,  2.70361106],
       [13.14158494,  9.9481314 , 10.41389235]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [129]:
x = np.random.uniform(1,16, size=(2,2,4))
x

array([[[ 2.53821335, 12.14184242,  3.3129042 , 14.98312152],
        [14.23254651,  4.24393605,  3.09356865,  3.68343575]],

       [[ 4.8646381 , 15.97689578, 12.01304387,  4.57046709],
        [13.95918413,  3.34650505, 13.61475033, 11.40366844]]])

33. Swap axes of the array you created in Question 32

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [168]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
a = np.sqrt(arr)
for element in a:
    if element < 0.5:
        element = 0
a

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [180]:
arr1 = np.random.randn(12)
arr2 = np.random.randn(12)
maximum = np.array([])
maximum = arr1.max(), arr2.max()
maximum

(1.4943808574690827, 1.6080442919191427)

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [186]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
a = np.unique(names)
a

array(['Bob', 'Joe', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [219]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
#for i in a:
#    for h in b:
#        if i == h:
#            np.numpy.setdiff1d(a)
a[b[np.searchsorted(b,a)] !=  a]         

array([1, 2, 3, 4])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [233]:
print("Printing Original array")
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]]) 
print (sampleArray)

print("Array after deleting column 2 on axis 1")
sampleArray = np.delete(sampleArray , 1, axis = 1) 
print (sampleArray)

arr = np.array([[10,10,10]])

print("Array after inserting column 2 on axis 1")
sampleArray = np.insert(sampleArray , 1, arr, axis = 1) 
print (sampleArray)

Printing Original array
[[34 43 73]
 [82 22 12]
 [53 94 66]]
Array after deleting column 2 on axis 1
[[34 73]
 [82 12]
 [53 66]]
Array after inserting column 2 on axis 1
[[34 10 73]
 [82 10 12]
 [53 10 66]]


39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [239]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
print(x)
print("--------------------------")
y = np.array([[6., 23.], [-1, 7], [8, 9]])
print(y)
answer = np.dot(x,y)
print("............................")
print(answer)

[[1. 2. 3.]
 [4. 5. 6.]]
--------------------------
[[ 6. 23.]
 [-1.  7.]
 [ 8.  9.]]
............................
[[ 28.  64.]
 [ 67. 181.]]


40. Generate a matrix of 20 random values and find its cumulative sum

In [248]:
random = np.random.randn(20)
np.cumsum(random)
random

array([ 1.35289949, -0.72706272,  0.53607942, -0.5445301 ,  0.93382872,
        0.64491348, -0.8362953 ,  2.21474261, -0.37569714,  0.68097245,
        1.04369118,  0.13348098, -0.76424716,  1.29863534,  0.40072059,
       -0.13280087,  0.26118685, -2.00856161, -0.16419524, -0.65941513])